title: MY FIRST BLOG
author: SIDRA KHAN
email: sidrakhan.me.100@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 Hey there!! My Portfolio website😎.

# social links
twitter_username:sidrakhanme # DO NOT include the @ character, or else the build will fail!
github_username:  sidrakhandev # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
